stages:
  - deploy

deploy_ke_minikube:
  stage: deploy
  tags:
    - runner-drpl
  script:
    - export PATH=$PATH:/opt/homebrew/bin
    - echo "Membangun image aplikasi di Minikube..."
    - minikube image build -t web-portofolio:latest .
    - echo "Membuat atau memperbarui Deployment di Kubernetes..."
    - kubectl get deployment deploy-portofolio || kubectl create deployment deploy-portofolio --image=web-portofolio:latest
    - kubectl set image deployment/deploy-portofolio web-portofolio=web-portofolio:latest || true
    - kubectl rollout restart deployment deploy-portofolio
    - echo "Membuka port akses aplikasi..."
    - kubectl get service deploy-portofolio || kubectl expose deployment deploy-portofolio --type=NodePort --port=80
    - echo "Deploy Otomatis Berhasil!"
